# Generated by Django 4.2.19 on 2025-03-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.CharField(blank=True, help_text='вставьте ссылку', max_length=255, null=True, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='books',
            name='Page_Count',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='количество страниц'),
        ),
        migrations.AlterField(
            model_name='books',
            name='Word_Count',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='год'),
        ),
    ]
