# Generated by Django 4.2.19 on 2025-03-10 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_course_instructors_course_instructors'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallinks',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='project.instructors'),
        ),
    ]
