# Generated by Django 4.2.19 on 2025-03-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_sociallinks_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сайта')),
                ('logo', models.ImageField(upload_to='images', verbose_name='Лого')),
                ('phone1', models.CharField(help_text='Вы можете начать номер телефона с +996 (700) 700 700', max_length=20, verbose_name='Телефон')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
