# Generated by Django 4.2.19 on 2025-03-21 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_course_instructors'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='project.blog', verbose_name='Блог'),
        ),
    ]
