# Generated by Django 4.2.19 on 2025-03-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_reviews_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='settings',
            name='email2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='settings',
            name='phone2',
            field=models.CharField(blank=True, help_text='Вы можете начать номер телефона с +996 (500) 700 700', max_length=20, null=True, verbose_name='Телефон'),
        ),
    ]
